
<div data-bind="scope: 'randomComment'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "randomComment": {
                    "component": "Training_CommentsAjax/js/comment",
                    "config": {
                        "template": "Training_CommentsAjax/comment",
                        "url": <?= json_encode($block->getUrl('commentsajax/index/index')) ?>
                    }
                }
            }
        }
    }
}
</script>
