<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var  $viewModel Training\QuantityAjax\ViewModel\CurrentProduct */
$viewModel = $block->getViewModel();

/** @var $_block \Magento\Catalog\Block\Product\View */
var_dump($_block); die;
$_product = $_block->getProduct();
var_dump($_product->urlEncoder); die;
?>

<div data-bind="scope: 'qtyProduct'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "qtyProduct": {
                    "component": "Training_QuantityAjax/js/qtyproduct",
                    "config": {
                        "template": "Training_QuantityAjax/qty",
                        "product_id": "<?= $viewModel->getProductId($_product); ?>"
                        "url": <?= json_encode($block->getUrl('quantityajax/index/index')) ?>
                    }
                }
            }
        }
    }
}


</script>
