<?php
///** @var Magento\Framework\View\Element\Template $block */
/** @var  Magento\Catalog\Block\Product\View $block */
$viewModel = $block->getVModel();
$product = $block->getProduct();
$productId = $product->getId();
?>
<div data-bind="scope: 'qtyProduct'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "qtyProduct": {
                    "component": "Training_QuantityAjax/js/qtyproduct",
                    "config": {
                        "template": "Training_QuantityAjax/qty",
                        "product_id": <?= $productId ?>,
                        "url": <?= json_encode($block->getUrl('quantityajax/index/index')) ?>
                    }
                }
            }
        }
    }
}
</script>
